name: Python Test

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Pull Git LFS objects
      run: git lfs pull
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: Debug Checkpoint Metadata
      run: |
        echo "Listing contents of snapshot directory:"
        ls -la tests/baseline_data/tank_model_snapshot/checkpoint_75000/
        echo "Content of _CHECKPOINT_METADATA:"
        cat tests/baseline_data/tank_model_snapshot/checkpoint_75000/_CHECKPOINT_METADATA
      shell: bash

    - name: Test with pytest
      run: |
        pytest
      env:
        PYTHONPATH: .
